### ISSUE TITLE
[Feature Request] Increase FM/PM operator frequency range beyond 0 and +12 semitones

### ISSUE THREAD

**Issue by unfa** [TheWaveWarden/odin2#329]
When using FM synthesis I often play a lot with octaves, as it's the only interval we can use between operators that's going to produce fully harmonic results. However in Odin2 the FM oscilaltor allows choosing pitch of an operator only between +0 and +12 semitones, so we're effectively having just one octave of range to work with, which is very limiting.
I think it'd be ideal to have a range between -48 and +48 (4 octaves up and down, 8 octaves total span). This shouldn't really affect the UI that much, but would allow a lot more sound design freedom.

What do you think?

**Comment by TheWaveWarden** [comment]
Basically a one-line change. I have to test it though - I don't remember why I chose those particular limits.

**Comment by TheWaveWarden** [comment]
https://github.com/TheWaveWarden/odin2/blob/2a735ad2fff0e3f0830ec5fa16ab6139e8c80513/Source/gui/OscComponent.cpp#L695

https://github.com/TheWaveWarden/odin2/blob/2a735ad2fff0e3f0830ec5fa16ab6139e8c80513/Source/gui/OscComponent.cpp#L707

**Comment by TheWaveWarden** [comment]
@unfa I just realilzed there is some confusion here as well:

The amounts do not represent semitones for the oscillatos, but the ratio the modulator has to the carrier. (See [manual](https://www.thewavewarden.com/assets/Odin2.2_manual.pdf) page 19) I.e. choosing values Carrier = 1 and Modulator = 12 means the carrier is 12 times the freq of the carrier. This is already 3.5849 octaves, so it actually is in the range you suggested already. I'm not too certain counting these in semitones would result in musical behaviour due to the nature of FM.

Anyway: I see how using the number 12 here introduces a false perception of semitones. I will test it with higher values anyway and probably at least bump it to 4 octaves (16).

**Comment by TheWaveWarden** [comment]
https://github.com/TheWaveWarden/odin2/commit/9b449b9d6d6dccceca0ed4a56a6c235dfdd8cbbe
