### ISSUE TITLE
[Feature Request] Accessing watetable position in other oscillators

### ISSUE THREAD

**Issue by unfa** [TheWaveWarden/odin2#334]
Currently it's possible to use a wavetable in Multi Oscillator, Vector Oscillator, FM and PM oscillators.

However - selecting a wavetable seems to only let the user access the first frame of the wavetable, apparently with no way to alter the wavetable position. It could be a very useful to be able to affect that.

**Comment by TheWaveWarden** [comment]
Hi @unfa,

The wavetables in the Wavetable and Multi oscillator are always composed of four single wavetables. The WT-Position knob only fades through those four.

In the other wavetables, you can select each of these individual frames. They are labeled "Glass 1" through "Glass 4". Therefore you **can** access all wavetables in each of the modules. Just the blending part is reserved for the Multi and Wavetable Modules. 

Using the blending in other oscs would need considerable redesign of the GUI layout. In case of the Vector it is redundant, because it can blend waves by itself.

**Comment by unfa** [comment]
Oh, that's how it works!
I thought the wavetables have more frames than just 4 :D
