### ISSUE TITLE
[Feature Request] visual feedback for (matrix)  modulated targets

### ISSUE THREAD

**Issue by ulibs66** [TheWaveWarden/odin2#356]
I am getting visual feedback for the target when the modulation source is assigned by midi learn but not if assigned by the modmatrix. Wouldnt' it be useful to have visual fb for both?

**Comment by TheWaveWarden** [comment]
This is due to the nature of how modulation and "adjusting by hand works". Using modulation on a parameter which is also available as a knob does not mean it simply "turns that knob by x degrees". Often times, setting the parameter costs lots of resources, becuase it uses an exponential or log function. This is very bad at audio range (which the modulation is), so Odin does some tricks around it to not call that expensive function on every sample. The result is that modmatrix has no consistent mapping to knob rotation.

Therefore I don't see this as a possibility!
