### ISSUE TITLE
Rename deb package!

### ISSUE THREAD

**Issue by mitscherdinger** [TheWaveWarden/odin2#373]
Hi!
There is already a package called "odin" in the repository of debian (also ubuntu?) and this can cause trouble. Please consider to rename the deb package to some other name like "odin-synth" or "odin2-synth" that the two packages can be confused!

**Comment by TheWaveWarden** [comment]
hmm ok. Is this the odin programming language?

Also, will it not cause trouble if people install odin-synth, which replaces file by the former odin package?

**Comment by trebmuh** [comment]
@TheWaveWarden : you can check here: https://packages.debian.org/odin

> odin2-synth

:+1:

**Comment by A350** [comment]
yes, pls conflict same package debian buster: odin

**Comment by TheWaveWarden** [comment]
I changed the package name to `odin2-synth`. However, as I suspected, it gives error when trying to install, since it tries to change files of the former package `odin`.

When installing via terminal I get an error message. However far worse: When installing via the Ubuntu Software Install Dialog, **It won't install, but gives no error message, making it look like it was installed.** This is the worst possible outcome. I see people trying to install it and failing without even realizing it.

Anyone know how to circumvent this?

**Comment by TheWaveWarden** [comment]
Ok I figured it out. A line
```
Replaces: odin (<< 2_2.5)
```
in the control file of the package allows the new package to replace files of the old package. This also guarantees to not conflict with an install of the magnetic imaging odin package from the sources!

So package renaming will be part of the 2.3 release!
